kind: PersistentVolume
apiVersion: v1
metadata:
  name: audioid-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/Users/ayu/Study/Courses/CSCI5253/TermProject/storage/tmp'
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: mp3-pvc
spec:
    accessModes:
      - ReadWriteMany
    storageClassName: manual
    resources:
        requests:
            storage: 1Gi