VERSION=v1
DOCKERUSER=001cat

build:
	docker build -f Dockerfile-Website -t audioid-website .

# push:
# 	docker tag sentiment-rest $(DOCKERUSER)/sentiment-rest:$(VERSION)
# 	docker push $(DOCKERUSER)/sentiment-rest:$(VERSION)
# 	docker tag sentiment-rest $(DOCKERUSER)/sentiment-rest:latest
# 	docker push $(DOCKERUSER)/sentiment-rest:latest
